### PR TITLE
Comments - cleanup and typos

### PR DESCRIPTION
**Pull request by brianteeman**
Just tidying it up bit and fixing some typos - ready for someone to finish adding all the comments

### CODE REVIEW

**Comment by Hils** [comment]
A small typo (sorry)
-    \* Should the value being prepared be shown in a HTML context then

should be 'an' HTML context

line 23 of the dif

**Comment by brianteeman** [comment]
@Hils I fixed that - thanks

In future if you click on the line number and comment there it is faster for me to find it AND the comment gets "closed" when it is fixed

**Comment by Hils** [comment]
Thank you - I didn't realise that.

**Comment by laoneo** [comment]
Feeling sad about my bad english :sob:

**Comment by laoneo** [comment]
Branch needs an update, otherwise we can't merge.

**Pull request merged**
