### PR TITLE
Possible fix for #28

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #28

This set the directory to a folderlist with a base of /images instead of a free text field
Advantages are obvious 
Disadvantage is that it is a fixed root of images

### CODE REVIEW

**Comment by laoneo** [comment]
Instead of hardcoding **images** we can read the media manager setting and set that as root path

image

**Comment by brianteeman** [comment]
We can indeed use that for the root but the user still needs to be able to select a sub-directory

**Comment by laoneo** [comment]
Can you please update your branch, that I can merge it?

**Comment by brianteeman** [comment]
See #60

**Pull request closed without merging**
