### PR TITLE
Remove versions

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #36

Removes the Versions button from the toolbar for a Field as it has no functionality

### CODE REVIEW

**Comment by laoneo** [comment]
Instead of just removing, we should discuss if it makes sense to have a version button for custom fields. I would welcome it. If it is broken, then we need to fix it instead of just removing it.

**Comment by brianteeman** [comment]
Versions is only useful for content - tracking what content has changed - its useless for tracking what configuration has changed - not even sure if we can do that

**Comment by wilsonge** [comment]
I agree with Brian on this. However now I think about it we need to work out how versioning works for custom fields. But I guess that's for another issue.

**Comment by brianteeman** [comment]
Yes we do need to think about versions on the content of the fields but this is only the structure

Thanks for merging

**Pull request merged**
