### PR TITLE
postgresql - sql for install

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .
### Summary of Changes

postgresql - sql for install
### Testing Instructions

test on postgresql

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks so far. The update script is missing. Can you create it as well.

**Comment by alikon** [comment]
done https://github.com/joomla-projects/custom-fields/pull/173

**Comment by laoneo** [comment]
Thank you very much, we merged it with commit https://github.com/joomla/joomla-cms/pull/11833/commits/d6a1f1925e92ea632a55502e568b366b84836ca3. Now we need to find somebody who can do SQL server.

**Comment by alikon** [comment]
i can do the install & update .sql files for SQL server too, but i'm unable to test on that platform....

**Comment by laoneo** [comment]
Go for it, then we have at least the scripts available.

**Pull request closed without merging**
