### PR TITLE
Add new context for com_contact for contact form fields

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #110 .
#### Summary of Changes

Adds a new context for com_contact to specify fields for the contact form.
#### Testing Instructions
- Switch the context in the back end  on _Components -> Contacts -> Fields_ to Mail as seen in the picture
  image
- Create a field for the mail context
- Create a contact menu item with form enabled
#### Expected result

The contact form will show the new field as input and the value will be sent after the message.

### CODE REVIEW

**Comment by coolcat-creations** [comment]
I created a dropdown list with 2 options "Department A" and "Department B"
- it´s readonly and shows the first value instead of options - but i didn´t set it to readonly,
- i had to fill the email-field to have the contactform shown in frontend. 
  I would rename this field to "default email" address and if any field is set in the mail context there should be a dropdown to select which fieldvalue should be used for sending the mail, in future versions it would be awesome to be able to create an own email template.
- The title above the fields is "ROOT"
- BeforeDisplay / After Display / After Title don´t affects the position of the field

**Comment by laoneo** [comment]
1. Looks like a permission problem, please set edit field for the public and guest user group. Does it help?
2. Why do you want to assign more than one E-Mail address to a contact? Do you want to send then the mails to all addresses? On a first implementation I would not do that.
3. Can you please attach a screenshot? I can't image what you mean as I never had that issue.
4. We have here a different case as the form is displayed and not the output as on the article view.

**Comment by coolcat-creations** [comment]
1) Edit is set to allowed in public and in guest.
bildschirmfoto 2016-06-19 um 09 39 53

2) Let´s say i want to have one contact for a company with different departments and not one contact for each department. I would like to set then a dropdown where to send the mail to.

3) This is how it looks like in frontend (readonly)
bildschirmfoto 2016-06-19 um 09 37 54

4) The positioning fields should be hidden then in this context because if there is a setting the user thinks it should apply...

Thx !!!

**Comment by laoneo** [comment]
You need the edit value permission, not the edit.

**Comment by laoneo** [comment]
Did it work? Can I merge this one?

**Comment by coolcat-creations** [comment]
Missing the context dropdown in the newest merge, or isn´t it already merged? thx!!

**Comment by laoneo** [comment]
I'v tested it and it is still there:

image

**Comment by laoneo** [comment]
Would like to merge it, is all working as expected?

**Pull request merged**
